# Importation des jeux de root

store_backend_homepage:
    path:     /hello/{name}
    defaults: { _controller: StoreBackendBundle:Default:index }

# Pages Statics
store_backend_statics:
    resource: "@StoreBackendBundle/Resources/config/statics.yml"
    prefix:   /


# Nom de la route
store_backend_index:
    path: /dashboard #chemin/URI de la route
    defaults: { _controller: StoreBackendBundle:Main:index }
    # Le Controller et l'action appelée

# Page Boutique
store_backend_jewelers:
    resource: "@StoreBackendBundle/Resources/config/modules/jeweler.yml"
    prefix:   /jewelers

# Page Products
store_backend_products:
    resource: "@StoreBackendBundle/Resources/config/modules/product.yml"
    prefix:   /{_locale}/products
    requirements:            # {_locale} : argument spécial au routing reconnu par le système d'internationalisation de Symfony
      _locale: en|fr

# Page Categories
store_backend_categories: #nom du jeu de root
    resource: "@StoreBackendBundle/Resources/config/modules/category.yml"
    prefix:   /categories

# Page Commandes
store_backend_orders: #nom du jeu de root
    resource: "@StoreBackendBundle/Resources/config/modules/order.yml"
    prefix:   /orders

# Page CMS
store_backend_cms: #nom du jeu de root
    resource: "@StoreBackendBundle/Resources/config/modules/cms.yml"
    prefix:   /{_locale}/cms # argument {_locale} pour traduire tout mon module CMS au niveau du routing
    requirements:            # {_locale} : argument spécial au routing reconnu par le système d'internationalisation de Symfony
      _locale: en|fr

# Page Supplier
store_backend_suppliers: #nom du jeu de root
    resource: "@StoreBackendBundle/Resources/config/modules/supplier.yml"
    prefix:   /suppliers

# Page Slider
store_backend_slider: #nom du jeu de root
    resource: "@StoreBackendBundle/Resources/config/modules/slider.yml"
    prefix:   /slides
