Category:
    type: entity
    table: category
    indexes:
        jeweler_id:
            columns:
                - jeweler_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: true
            length: 300
            fixed: false
            comment: ''
        description:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        position:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        active:
            type: boolean
            nullable: true
            comment: ''
    manyToOne:
        jeweler:
            targetEntity: Jeweler
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                jeweler_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        product:
            targetEntity: Product
            cascade: {  }
            mappedBy: category
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
