Orders:
    type: entity
    table: orders
    indexes:
        user_id:
            columns:
                - user_id
        jeweler_id:
            columns:
                - jeweler_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        address:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        date:
            type: date
            nullable: true
            comment: ''
        total:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
        state:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        dateCreated:
            type: datetime
            nullable: false
            comment: ''
            column: date_created
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        jeweler:
            targetEntity: Jeweler
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                jeweler_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        product:
            targetEntity: Product
            cascade: {  }
            mappedBy: null
            inversedBy: order
            joinTable:
                name: order_detail
                joinColumns:
                    -
                        name: order_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: product_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
