store_backend:
    resource: "@StoreBackendBundle/Resources/config/routing.yml"
    prefix:   /administration



app:
    resource: "@AppBundle/Controller/"
    type:     annotation



# Subscribe Jeweler Backend

store_backend_security_subscribe:
    path: /subscribe
    defaults: { _controller: StoreBackendBundle:Security:subscribe }



# Login Backend

store_backend_security_login:
    path: /login
    defaults: { _controller: StoreBackendBundle:Security:login }



# Route de l'action de mon formulaire d'authentification

store_backend_security_login_check:
    path: /administration/login_check
    defaults: { _controller: StoreBackendBundle:Security:login }



# Logout Backend

store_backend_security_logout:
    path: /administration/logout