# Page List of Categories

store_backend_category_list: # Nom de la root -> Nom du namespace _ nom du bundle _ nom du controller _ nom de l'action du controller
      path:     /list # chemin vers l'URI
      defaults: { _controller: StoreBackendBundle:Category:list } # NomduBundle:NomduController:Nomdel'Action



# Page View a Category

store_backend_category_view:
      path: /view/{id}/{name} # id = argument (ou variable)
      defaults: { _controller: StoreBackendBundle:Category:view }
      requirements:
          id: \d+
          name: "[a-zA-Z0-9-]{5,30}"
          _method: GET



# Page New a Category

store_backend_category_new: # Nom de la route -> Nom du namespace _ nom du bundle _ nom du controller _ nom de l'action du controller
      path:     /new # chemin vers l'URI
      defaults: { _controller: StoreBackendBundle:Category:new } # NomduBundle:NomduController:Nomdel'Action



# Page Edit a Category

store_backend_category_edit:
      path: /edit/{id}
      defaults: { _controller: StoreBackendBundle:Category:edit }



# Remove a Category

store_backend_category_remove: # Nom de la route -> Nom du namespace _ nom du bundle _ nom du controller _ nom de l'action du controller
      path:     /remove/{id} # chemin vers l'URI
      defaults: { _controller: StoreBackendBundle:Category:remove } # NomduBundle:NomduController:Nomdel'Action



# Activate a Category

store_backend_category_activate: # Nom de la route -> Nom du namespace _ nom du bundle _ nom du controller _ nom de l'action du controller
      path: /activate/{id}/{action} # chemin vers l'URI
      defaults: { _controller: StoreBackendBundle:Category:activate } # NomduBundle:NomduController:Nomdel'Action

# Desactivate a Category

store_backend_category_desactivate: # Nom de la route -> Nom du namespace _ nom du bundle _ nom du controller _ nom de l'action du controller
      path: /desactivate/{id}/{action} # chemin vers l'URI
      defaults: { _controller: StoreBackendBundle:Category:desactivate } # NomduBundle:NomduController:Nomdel'Action


