# Page List of Orders

store_backend_order_list: # Nom de la root -> Nom du namespace _ nom du bundle _ nom du controller _ nom de l'action du controller
      path:     /list # chemin vers l'URI
      defaults: { _controller: StoreBackendBundle:Order:list } # NomduBundle:NomduController:Nomdel'Action